
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul 20 2024 13:36:57 CEST (Jul 20 2024 11:36:57 UTC)

// Verification Directory fv/PWM 

module PWM(clk, rst, inc, dec, pwm_reg, pwm_out, led);
  input clk, rst, inc, dec;
  input [9:0] pwm_reg;
  output pwm_out;
  output [9:0] led;
  wire clk, rst, inc, dec;
  wire [9:0] pwm_reg;
  wire pwm_out;
  wire [9:0] led;
  wire [9:0] temp_dty_cycle;
  wire [9:0] counter;
  wire [9:0] last_dty_cycle;
  wire n_1, n_2, n_3, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_81, n_82, n_83;
  wire n_84, n_85, n_87, n_95, n_97, n_100, n_101, n_108;
  wire n_111, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  assign led[0] = 1'b0;
  assign led[1] = 1'b0;
  assign led[2] = 1'b0;
  assign led[3] = 1'b0;
  assign led[4] = 1'b0;
  assign led[5] = 1'b0;
  assign led[6] = 1'b0;
  assign led[7] = 1'b0;
  assign led[8] = 1'b0;
  assign led[9] = 1'b0;
  DFFHQX1 \temp_dty_cycle_reg[9] (.CK (clk), .D (n_164), .Q
       (temp_dty_cycle[9]));
  DFFHQX1 \temp_dty_cycle_reg[5] (.CK (clk), .D (n_163), .Q
       (temp_dty_cycle[5]));
  OAI211X1 g4348__2398(.A0 (n_42), .A1 (n_162), .B0 (n_81), .C0
       (n_158), .Y (n_164));
  DFFQXL pwm_out_reg(.CK (clk), .D (n_161), .Q (pwm_out));
  DFFHQX1 \temp_dty_cycle_reg[6] (.CK (clk), .D (n_160), .Q
       (temp_dty_cycle[6]));
  DFFHQX1 \temp_dty_cycle_reg[8] (.CK (clk), .D (n_159), .Q
       (temp_dty_cycle[8]));
  OAI31X1 g4340__5107(.A0 (temp_dty_cycle[5]), .A1 (n_120), .A2
       (n_162), .B0 (n_156), .Y (n_163));
  DFFHQX1 \temp_dty_cycle_reg[4] (.CK (clk), .D (n_154), .Q
       (temp_dty_cycle[4]));
  DFFHQX1 \temp_dty_cycle_reg[7] (.CK (clk), .D (n_157), .Q
       (temp_dty_cycle[7]));
  DFFHQX1 \temp_dty_cycle_reg[3] (.CK (clk), .D (n_155), .Q
       (temp_dty_cycle[3]));
  OAI21X1 g4332__6260(.A0 (counter[9]), .A1 (n_7), .B0 (n_150), .Y
       (n_161));
  NAND2X1 g4341__4319(.A (n_137), .B (n_153), .Y (n_160));
  OAI221X1 g4356__8428(.A0 (n_1), .A1 (n_144), .B0 (temp_dty_cycle[8]),
       .B1 (n_131), .C0 (n_82), .Y (n_159));
  AOI22X1 g4354__5526(.A0 (temp_dty_cycle[9]), .A1 (n_149), .B0
       (temp_dty_cycle[8]), .B1 (n_129), .Y (n_158));
  OAI211X1 g4343__6783(.A0 (n_124), .A1 (n_147), .B0 (n_125), .C0
       (n_130), .Y (n_157));
  AOI222X1 g4344__3680(.A0 (n_133), .A1 (n_148), .B0 (pwm_reg[5]), .B1
       (n_152), .C0 (temp_dty_cycle[5]), .C1 (n_139), .Y (n_156));
  OAI211X1 g4365__1617(.A0 (n_145), .A1 (n_162), .B0 (n_100), .C0
       (n_146), .Y (n_155));
  INVXL g4346(.A (n_151), .Y (n_154));
  AOI221X1 g4347__2802(.A0 (pwm_reg[6]), .A1 (n_152), .B0
       (temp_dty_cycle[6]), .B1 (n_134), .C0 (n_122), .Y (n_153));
  AOI221X1 g4349__1705(.A0 (pwm_reg[4]), .A1 (n_152), .B0
       (temp_dty_cycle[4]), .B1 (n_141), .C0 (n_128), .Y (n_151));
  OAI222X1 g4342__5122(.A0 (temp_dty_cycle[9]), .A1 (n_52), .B0
       (temp_dty_cycle[8]), .B1 (n_136), .C0 (n_76), .C1 (n_135), .Y
       (n_150));
  DFFHQX1 \temp_dty_cycle_reg[2] (.CK (clk), .D (n_142), .Q
       (temp_dty_cycle[2]));
  OR2XL g4371__8246(.A (n_148), .B (n_143), .Y (n_149));
  INVX1 g4374(.A (n_138), .Y (n_147));
  AOI22X1 g4375__7098(.A0 (temp_dty_cycle[3]), .A1 (n_126), .B0
       (n_145), .B1 (n_148), .Y (n_146));
  AOI21X1 g4376__6131(.A0 (n_117), .A1 (n_148), .B0 (n_143), .Y
       (n_144));
  OAI221X1 g4364__1881(.A0 (n_59), .A1 (n_140), .B0
       (temp_dty_cycle[2]), .B1 (n_123), .C0 (n_83), .Y (n_142));
  OAI211X1 g4377__5115(.A0 (n_19), .A1 (n_162), .B0 (n_115), .C0
       (n_140), .Y (n_141));
  OAI211X1 g4378__7482(.A0 (n_32), .A1 (n_132), .B0 (n_127), .C0
       (n_140), .Y (n_139));
  OAI211X1 g4380__4733(.A0 (n_51), .A1 (n_162), .B0 (n_137), .C0
       (n_140), .Y (n_138));
  NOR2BX1 g4363__6161(.AN (n_135), .B (counter[8]), .Y (n_136));
  OAI221X1 g4379__9315(.A0 (n_121), .A1 (n_162), .B0 (n_133), .B1
       (n_132), .C0 (n_140), .Y (n_134));
  NOR2BX1 g4382__9945(.AN (n_130), .B (n_129), .Y (n_131));
  OAI31X1 g4383__2883(.A0 (temp_dty_cycle[4]), .A1 (n_114), .A2
       (n_132), .B0 (n_127), .Y (n_128));
  OAI21X1 g4384__2346(.A0 (n_118), .A1 (n_162), .B0 (n_140), .Y
       (n_143));
  NOR2X1 g4373__1666(.A (n_47), .B (n_116), .Y (n_135));
  INVX1 g4391(.A (n_140), .Y (n_126));
  AOI32X1 g4408__7410(.A0 (n_124), .A1 (n_113), .A2 (n_148), .B0
       (pwm_reg[7]), .B1 (n_152), .Y (n_125));
  NOR2XL g4392__6417(.A (n_148), .B (n_119), .Y (n_123));
  NOR3BX1 g4393__5477(.AN (n_121), .B (temp_dty_cycle[6]), .C (n_162),
       .Y (n_122));
  NAND2X1 g4389__2398(.A (n_120), .B (n_119), .Y (n_127));
  DFFHQX1 \last_dty_cycle_reg[2] (.CK (clk), .D (n_187), .Q
       (last_dty_cycle[2]));
  NAND2X1 g4388__5107(.A (n_118), .B (n_119), .Y (n_130));
  DFFHQX1 \last_dty_cycle_reg[9] (.CK (clk), .D (n_190), .Q
       (last_dty_cycle[9]));
  DFFHQX1 \last_dty_cycle_reg[6] (.CK (clk), .D (n_111), .Q
       (last_dty_cycle[6]));
  NAND3X1 g4394__6260(.A (n_101), .B (n_180), .C (n_162), .Y (n_140));
  NOR2X1 g4426__4319(.A (n_117), .B (n_132), .Y (n_129));
  DFFHQX1 \last_dty_cycle_reg[3] (.CK (clk), .D (n_183), .Q
       (last_dty_cycle[3]));
  DFFHQX1 \last_dty_cycle_reg[5] (.CK (clk), .D (n_184), .Q
       (last_dty_cycle[5]));
  DFFHQX1 \last_dty_cycle_reg[8] (.CK (clk), .D (n_188), .Q
       (last_dty_cycle[8]));
  DFFHQX1 \last_dty_cycle_reg[7] (.CK (clk), .D (n_185), .Q
       (last_dty_cycle[7]));
  DFFHQX1 \last_dty_cycle_reg[4] (.CK (clk), .D (n_108), .Q
       (last_dty_cycle[4]));
  DFFHQX1 \last_dty_cycle_reg[1] (.CK (clk), .D (n_186), .Q
       (temp_dty_cycle[1]));
  DFFHQX1 \last_dty_cycle_reg[0] (.CK (clk), .D (n_189), .Q
       (temp_dty_cycle[0]));
  OAI222X1 g4386__8428(.A0 (temp_dty_cycle[7]), .A1 (n_23), .B0 (n_46),
       .B1 (n_85), .C0 (temp_dty_cycle[6]), .C1 (n_61), .Y (n_116));
  NAND2X1 g4414__5526(.A (n_114), .B (n_148), .Y (n_115));
  NAND2BX1 g4425__6783(.AN (n_113), .B (n_148), .Y (n_137));
  NOR2X1 g4415__1617(.A (rst), .B (n_5), .Y (n_111));
  INVX1 g4396(.A (n_162), .Y (n_119));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_95), .Q (counter[9]));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_87), .Q (counter[7]));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_84), .Q (counter[8]));
  NOR2X1 g4418__5122(.A (rst), .B (n_8), .Y (n_108));
  INVX1 g4428(.A (n_148), .Y (n_132));
  NOR2BX1 g4436__7482(.AN (n_180), .B (n_101), .Y (n_148));
  NAND2X1 g4398__4733(.A (n_180), .B (n_71), .Y (n_162));
  NAND2X1 g4435__6161(.A (pwm_reg[3]), .B (n_152), .Y (n_100));
  NOR2X1 g4328__9315(.A (n_181), .B (n_78), .Y (n_95));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_67), .Q (counter[3]));
  NOR2X1 g4327__9945(.A (n_181), .B (n_72), .Y (n_87));
  OAI211X1 g4395__2883(.A0 (counter[3]), .A1 (n_9), .B0 (n_20), .C0
       (n_66), .Y (n_85));
  NOR2XL g4333__2346(.A (n_181), .B (n_77), .Y (n_84));
  NAND2X1 g4432__1666(.A (pwm_reg[2]), .B (n_152), .Y (n_83));
  NAND2X1 g4431__7410(.A (pwm_reg[8]), .B (n_152), .Y (n_82));
  NAND2X1 g4430__6417(.A (pwm_reg[9]), .B (n_152), .Y (n_81));
  DFFHQX1 \counter_reg[0] (.CK (clk), .D (n_69), .Q (counter[0]));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_79), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_68), .Q (counter[2]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_70), .Q (counter[5]));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_73), .Q (counter[4]));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_74), .Q (counter[6]));
  NOR2X1 g4372__2398(.A (n_22), .B (n_181), .Y (n_79));
  AOI21X1 g4334__5107(.A0 (counter[8]), .A1 (n_75), .B0 (counter[9]),
       .Y (n_78));
  MXI2XL g4350__6260(.A (counter[8]), .B (n_76), .S0 (n_75), .Y (n_77));
  NOR2X1 g4339__4319(.A (n_181), .B (n_65), .Y (n_74));
  NOR2X1 g4381__8428(.A (n_45), .B (n_181), .Y (n_73));
  NOR2X1 g4447__5526(.A (rst), .B (n_97), .Y (n_152));
  XNOR2X1 g4335__6783(.A (counter[7]), .B (n_63), .Y (n_72));
  NOR3BXL g4409__3680(.AN (dec), .B (inc), .C (n_64), .Y (n_71));
  NOR2X1 g4362__1617(.A (n_58), .B (n_181), .Y (n_70));
  NOR2X1 g4368__2802(.A (counter[0]), .B (n_181), .Y (n_69));
  NOR2X1 g4369__1705(.A (n_31), .B (n_181), .Y (n_68));
  NOR2X1 g4370__5122(.A (n_40), .B (n_181), .Y (n_67));
  OAI211X1 g4407__8246(.A0 (temp_dty_cycle[3]), .A1 (n_39), .B0 (n_57),
       .C0 (n_60), .Y (n_66));
  AND3XL g4453__7098(.A (n_13), .B (n_16), .C (n_54), .Y (n_97));
  XNOR2X1 g4355__6131(.A (counter[6]), .B (n_62), .Y (n_65));
  NOR4X1 g4434__5115(.A (temp_dty_cycle[8]), .B (temp_dty_cycle[9]), .C
       (temp_dty_cycle[7]), .D (n_49), .Y (n_64));
  OAI211X1 g4450__7482(.A0 (n_124), .A1 (n_48), .B0 (inc), .C0 (n_2),
       .Y (n_101));
  AND2XL g4366__4733(.A (counter[6]), .B (n_62), .Y (n_63));
  NOR2BX1 g4367__6161(.AN (n_62), .B (n_61), .Y (n_75));
  OAI31X1 g4433__9315(.A0 (counter[2]), .A1 (n_56), .A2 (n_55), .B0
       (n_59), .Y (n_60));
  XNOR2X1 g4385__9945(.A (counter[5]), .B (n_50), .Y (n_58));
  OAI21X1 g4448__2883(.A0 (n_56), .A1 (n_55), .B0 (counter[2]), .Y
       (n_57));
  NOR3XL g4455__2346(.A (n_27), .B (n_34), .C (n_37), .Y (n_54));
  NAND2X1 g4458__1666(.A (temp_dty_cycle[7]), .B (n_113), .Y (n_117));
  NOR4X1 g4397__7410(.A (n_52), .B (n_76), .C (n_61), .D (n_36), .Y
       (n_53));
  AND2XL g4459__6417(.A (n_124), .B (n_51), .Y (n_118));
  AND2XL g4390__5477(.A (counter[5]), .B (n_50), .Y (n_62));
  NOR2X1 g4454__2398(.A (n_43), .B (n_38), .Y (n_49));
  INVX1 g4460(.A (n_44), .Y (n_48));
  AOI221X1 g4462__5107(.A0 (n_29), .A1 (n_182), .B0
       (temp_dty_cycle[5]), .B1 (n_30), .C0 (n_46), .Y (n_47));
  XNOR2X1 g4406__6260(.A (counter[4]), .B (n_41), .Y (n_45));
  AOI31X1 g4461__4319(.A0 (n_43), .A1 (n_33), .A2 (n_120), .B0 (n_42),
       .Y (n_44));
  NAND2X1 g4464__8428(.A (temp_dty_cycle[6]), .B (n_121), .Y (n_51));
  AND2XL g4427__5526(.A (counter[4]), .B (n_41), .Y (n_50));
  NAND2X1 g4465__6783(.A (n_43), .B (n_133), .Y (n_113));
  MXI2XL g4449__3680(.A (counter[3]), .B (n_39), .S0 (n_35), .Y (n_40));
  OAI22X1 g4456__1617(.A0 (temp_dty_cycle[1]), .A1 (n_26), .B0
       (temp_dty_cycle[0]), .B1 (n_21), .Y (n_55));
  OAI31X1 g4457__2802(.A0 (temp_dty_cycle[4]), .A1 (temp_dty_cycle[3]),
       .A2 (n_18), .B0 (temp_dty_cycle[5]), .Y (n_38));
  NAND4XL g4469__1705(.A (n_25), .B (n_11), .C (n_14), .D (n_17), .Y
       (n_37));
  NOR3X1 g4424__5122(.A (counter[4]), .B (counter[3]), .C (n_35), .Y
       (n_36));
  OAI211X1 g4468__8246(.A0 (pwm_reg[4]), .A1 (n_6), .B0 (n_12), .C0
       (n_15), .Y (n_34));
  NOR2BX1 g4451__7098(.AN (n_35), .B (n_39), .Y (n_41));
  NOR2X1 g4470__6131(.A (n_33), .B (n_120), .Y (n_121));
  AND2X1 g4472__1881(.A (n_32), .B (n_33), .Y (n_133));
  XNOR2X1 g4463__5115(.A (counter[2]), .B (n_56), .Y (n_31));
  OR2XL g4476__7482(.A (n_29), .B (n_182), .Y (n_30));
  OAI222X1 g4471__4733(.A0 (n_5), .A1 (last_dty_cycle[6]), .B0
       (pwm_reg[6]), .B1 (n_3), .C0 (n_8), .C1 (last_dty_cycle[4]), .Y
       (n_27));
  NOR3X1 g4467__6161(.A (counter[1]), .B (counter[0]), .C (n_24), .Y
       (n_26));
  MXI2XL g4474__9315(.A (temp_dty_cycle[0]), .B (n_24), .S0
       (pwm_reg[0]), .Y (n_25));
  AOI21X1 g4475__9945(.A0 (counter[6]), .A1 (n_43), .B0 (counter[7]),
       .Y (n_23));
  OAI22X1 g4477__2883(.A0 (counter[7]), .A1 (n_124), .B0 (counter[6]),
       .B1 (n_43), .Y (n_46));
  AND2XL g4466__2346(.A (counter[2]), .B (n_56), .Y (n_35));
  MX2XL g4481__1666(.A (n_21), .B (counter[1]), .S0 (counter[0]), .Y
       (n_22));
  AOI22X1 g4489__7410(.A0 (temp_dty_cycle[5]), .A1 (n_29), .B0
       (temp_dty_cycle[4]), .B1 (n_10), .Y (n_20));
  NOR2BX1 g4478__6417(.AN (n_114), .B (n_19), .Y (n_145));
  NAND2BX1 g4479__5477(.AN (n_114), .B (temp_dty_cycle[4]), .Y (n_32));
  NOR2BX1 g4480__2398(.AN (n_19), .B (temp_dty_cycle[4]), .Y (n_120));
  AOI2BB1XL g4473__5107(.A0N (temp_dty_cycle[1]), .A1N
       (temp_dty_cycle[0]), .B0 (n_59), .Y (n_18));
  XNOR2X1 g4484__6260(.A (pwm_reg[1]), .B (temp_dty_cycle[1]), .Y
       (n_17));
  XNOR2X1 g4483__4319(.A (pwm_reg[9]), .B (last_dty_cycle[9]), .Y
       (n_16));
  XNOR2X1 g4482__8428(.A (pwm_reg[7]), .B (last_dty_cycle[7]), .Y
       (n_15));
  XNOR2X1 g4487__5526(.A (pwm_reg[3]), .B (last_dty_cycle[3]), .Y
       (n_14));
  XNOR2X1 g4486__6783(.A (pwm_reg[8]), .B (last_dty_cycle[8]), .Y
       (n_13));
  XNOR2X1 g4485__3680(.A (pwm_reg[5]), .B (last_dty_cycle[5]), .Y
       (n_12));
  XNOR2X1 g4488__1617(.A (pwm_reg[2]), .B (last_dty_cycle[2]), .Y
       (n_11));
  NAND2X1 g4492__1705(.A (counter[6]), .B (counter[7]), .Y (n_61));
  NAND2X1 g4494__5122(.A (temp_dty_cycle[2]), .B (temp_dty_cycle[3]),
       .Y (n_114));
  NAND2X1 g4490__8246(.A (temp_dty_cycle[8]), .B (temp_dty_cycle[9]),
       .Y (n_42));
  NOR2X1 g4491__7098(.A (temp_dty_cycle[2]), .B (temp_dty_cycle[3]), .Y
       (n_19));
  AND2X1 g4495__6131(.A (counter[1]), .B (counter[0]), .Y (n_56));
  INVX1 g4501(.A (counter[4]), .Y (n_10));
  INVX1 g4512(.A (temp_dty_cycle[3]), .Y (n_9));
  INVX1 g4509(.A (pwm_reg[4]), .Y (n_8));
  INVX1 g4511(.A (temp_dty_cycle[9]), .Y (n_7));
  INVX1 g4498(.A (last_dty_cycle[4]), .Y (n_6));
  INVX1 g4510(.A (counter[1]), .Y (n_21));
  INVX1 g4504(.A (temp_dty_cycle[0]), .Y (n_24));
  INVX1 g4499(.A (counter[9]), .Y (n_52));
  INVX1 g4513(.A (counter[3]), .Y (n_39));
  INVX1 g4505(.A (counter[8]), .Y (n_76));
  INVX1 g4500(.A (pwm_reg[6]), .Y (n_5));
  INVX1 g4497(.A (last_dty_cycle[6]), .Y (n_3));
  INVX1 g4496(.A (dec), .Y (n_2));
  INVX1 g4502(.A (temp_dty_cycle[8]), .Y (n_1));
  INVX1 g4515(.A (temp_dty_cycle[5]), .Y (n_33));
  INVX1 g4503(.A (temp_dty_cycle[2]), .Y (n_59));
  INVX1 g4514(.A (counter[5]), .Y (n_29));
  INVX1 g4507(.A (temp_dty_cycle[7]), .Y (n_124));
  INVX1 g4516(.A (temp_dty_cycle[6]), .Y (n_43));
  NOR2BX1 g2(.AN (n_97), .B (rst), .Y (n_180));
  AO21X1 g4556(.A0 (counter[5]), .A1 (n_53), .B0 (rst), .Y (n_181));
  NAND2BX1 g4557(.AN (temp_dty_cycle[4]), .B (counter[4]), .Y (n_182));
  NOR2BX1 g4558(.AN (pwm_reg[3]), .B (rst), .Y (n_183));
  NOR2BX1 g4559(.AN (pwm_reg[5]), .B (rst), .Y (n_184));
  NOR2BX1 g4560(.AN (pwm_reg[7]), .B (rst), .Y (n_185));
  NOR2BX1 g4561(.AN (pwm_reg[1]), .B (rst), .Y (n_186));
  NOR2BX1 g4562(.AN (pwm_reg[2]), .B (rst), .Y (n_187));
  NOR2BX1 g4563(.AN (pwm_reg[8]), .B (rst), .Y (n_188));
  NOR2BX1 g4564(.AN (pwm_reg[0]), .B (rst), .Y (n_189));
  NOR2BX1 g4565(.AN (pwm_reg[9]), .B (rst), .Y (n_190));
endmodule

