
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul 19 2024 13:10:31 CEST (Jul 19 2024 11:10:31 UTC)

// Verification Directory fv/uart_rx 

module uart_rx(clk, rst, UART_CPB, rx_serial, UART_RDR, rx_done);
  input clk, rst, rx_serial;
  input [15:0] UART_CPB;
  output [7:0] UART_RDR;
  output rx_done;
  wire clk, rst, rx_serial;
  wire [15:0] UART_CPB;
  wire [7:0] UART_RDR;
  wire rx_done;
  wire [15:0] cntr;
  wire [3:0] bitcntr;
  wire [8:0] rx_buffer;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_147, state;
  assign rx_done = 1'b1;
  DFFHQX1 \cntr_reg[15] (.CK (clk), .D (n_127), .Q (cntr[15]));
  OAI31X1 g4249__2398(.A0 (cntr[15]), .A1 (n_123), .A2 (n_125), .B0
       (n_126), .Y (n_127));
  DFFHQX1 \cntr_reg[14] (.CK (clk), .D (n_124), .Q (cntr[14]));
  DFFHQX1 \cntr_reg[13] (.CK (clk), .D (n_122), .Q (cntr[13]));
  OAI211X1 g4251__5107(.A0 (n_119), .A1 (n_125), .B0 (cntr[15]), .C0
       (n_118), .Y (n_126));
  OAI31X1 g4252__6260(.A0 (cntr[14]), .A1 (n_123), .A2 (n_121), .B0
       (n_120), .Y (n_124));
  OAI32X1 g4254__4319(.A0 (cntr[13]), .A1 (n_116), .A2 (n_121), .B0
       (n_123), .B1 (n_115), .Y (n_122));
  DFFHQX1 \cntr_reg[12] (.CK (clk), .D (n_117), .Q (cntr[12]));
  OAI211X1 g4253__8428(.A0 (n_119), .A1 (n_121), .B0 (cntr[14]), .C0
       (n_118), .Y (n_120));
  DFFHQX1 \cntr_reg[8] (.CK (clk), .D (n_102), .Q (cntr[8]));
  DFFHQX1 \cntr_reg[9] (.CK (clk), .D (n_107), .Q (cntr[9]));
  DFFHQX1 \cntr_reg[7] (.CK (clk), .D (n_113), .Q (cntr[7]));
  DFFHQX1 \cntr_reg[11] (.CK (clk), .D (n_114), .Q (cntr[11]));
  DFFHQX1 \cntr_reg[10] (.CK (clk), .D (n_110), .Q (cntr[10]));
  DFFHQX1 \cntr_reg[6] (.CK (clk), .D (n_111), .Q (cntr[6]));
  NOR2X1 g4257__5526(.A (n_116), .B (n_112), .Y (n_117));
  NAND2X1 g4256__6783(.A (cntr[14]), .B (n_115), .Y (n_125));
  DFFHQX1 \cntr_reg[1] (.CK (clk), .D (n_103), .Q (cntr[1]));
  DFFHQX1 \cntr_reg[0] (.CK (clk), .D (n_106), .Q (cntr[0]));
  DFFHQX1 \cntr_reg[2] (.CK (clk), .D (n_105), .Q (cntr[2]));
  DFFHQX1 \cntr_reg[3] (.CK (clk), .D (n_104), .Q (cntr[3]));
  DFFHQX1 \cntr_reg[4] (.CK (clk), .D (n_109), .Q (cntr[4]));
  DFFHQX1 \cntr_reg[5] (.CK (clk), .D (n_108), .Q (cntr[5]));
  DFFQXL \bitcntr_reg[3] (.CK (clk), .D (n_99), .Q (bitcntr[3]));
  NAND2X1 g4301__3680(.A (cntr[13]), .B (n_118), .Y (n_123));
  DFFHQX1 state_reg(.CK (clk), .D (n_100), .Q (state));
  NOR2X1 g4262__1617(.A (n_116), .B (n_95), .Y (n_114));
  NOR2XL g4278__2802(.A (n_80), .B (n_116), .Y (n_113));
  XNOR2X1 g4260__1705(.A (cntr[12]), .B (n_101), .Y (n_112));
  NOR2XL g4282__5122(.A (n_75), .B (n_116), .Y (n_111));
  NOR2XL g4266__8246(.A (n_88), .B (n_116), .Y (n_110));
  DFFQXL \bitcntr_reg[2] (.CK (clk), .D (n_96), .Q (bitcntr[2]));
  INVX1 g4258(.A (n_121), .Y (n_115));
  DFFHQX1 \bitcntr_reg[1] (.CK (clk), .D (n_94), .Q (bitcntr[1]));
  NOR2XL g4304__7098(.A (n_69), .B (n_116), .Y (n_109));
  NOR2XL g4291__6131(.A (n_73), .B (n_116), .Y (n_108));
  NOR2XL g4270__1881(.A (n_84), .B (n_116), .Y (n_107));
  NOR2XL g4297__5115(.A (cntr[0]), .B (n_116), .Y (n_106));
  NOR2XL g4298__7482(.A (n_53), .B (n_116), .Y (n_105));
  NOR2XL g4300__4733(.A (n_64), .B (n_116), .Y (n_104));
  NOR2XL g4303__6161(.A (n_12), .B (n_116), .Y (n_103));
  NOR2XL g4274__9315(.A (n_82), .B (n_116), .Y (n_102));
  SDFFQX1 \bitcntr_reg[0] (.CK (clk), .D (n_97), .SI (n_98), .SE
       (bitcntr[0]), .Q (bitcntr[0]));
  INVX1 g4307(.A (n_116), .Y (n_118));
  NAND2X1 g4261__9945(.A (cntr[12]), .B (n_101), .Y (n_121));
  AND2XL g4299__2883(.A (rst), .B (n_91), .Y (n_100));
  AO22XL g4302__2346(.A0 (bitcntr[3]), .A1 (n_98), .B0 (n_60), .B1
       (n_97), .Y (n_99));
  OAI22X1 g4306__1666(.A0 (n_39), .A1 (n_93), .B0 (n_40), .B1 (n_92),
       .Y (n_96));
  OAI2BB1X1 g4308__7410(.A0N (rx_serial), .A1N (n_90), .B0 (n_98), .Y
       (n_116));
  XNOR2X1 g4264__6417(.A (cntr[11]), .B (n_89), .Y (n_95));
  OAI22X1 g4305__5477(.A0 (n_21), .A1 (n_93), .B0 (n_18), .B1 (n_92),
       .Y (n_94));
  MXI2XL g4309__2398(.A (state), .B (n_90), .S0 (n_86), .Y (n_91));
  AND2XL g4265__5107(.A (cntr[11]), .B (n_89), .Y (n_101));
  INVX1 g4312(.A (n_93), .Y (n_98));
  XNOR2X1 g4268__6260(.A (cntr[10]), .B (n_87), .Y (n_88));
  SDFFQX1 \rx_buffer_reg[8] (.CK (clk), .D (rx_serial), .SI
       (rx_buffer[8]), .SE (n_92), .Q (rx_buffer[8]));
  SDFFQX1 \rx_buffer_reg[0] (.CK (clk), .D (rx_buffer[1]), .SI
       (rx_buffer[0]), .SE (n_92), .Q (rx_buffer[0]));
  OAI211X1 g4313__4319(.A0 (n_90), .A1 (n_78), .B0 (rst), .C0 (n_85),
       .Y (n_93));
  SDFFQX1 \rx_buffer_reg[1] (.CK (clk), .D (rx_buffer[2]), .SI
       (rx_buffer[1]), .SE (n_92), .Q (rx_buffer[1]));
  SDFFQX1 \rx_buffer_reg[2] (.CK (clk), .D (rx_buffer[3]), .SI
       (rx_buffer[2]), .SE (n_92), .Q (rx_buffer[2]));
  AND2XL g4269__8428(.A (cntr[10]), .B (n_87), .Y (n_89));
  SDFFQX1 \rx_buffer_reg[4] (.CK (clk), .D (rx_buffer[5]), .SI
       (rx_buffer[4]), .SE (n_92), .Q (rx_buffer[4]));
  SDFFQX1 \rx_buffer_reg[5] (.CK (clk), .D (rx_buffer[6]), .SI
       (rx_buffer[5]), .SE (n_92), .Q (rx_buffer[5]));
  SDFFQX1 \rx_buffer_reg[7] (.CK (clk), .D (rx_buffer[8]), .SI
       (rx_buffer[7]), .SE (n_92), .Q (rx_buffer[7]));
  SDFFQX1 \rx_buffer_reg[6] (.CK (clk), .D (rx_buffer[7]), .SI
       (rx_buffer[6]), .SE (n_92), .Q (rx_buffer[6]));
  SDFFQX1 \rx_buffer_reg[3] (.CK (clk), .D (rx_buffer[4]), .SI
       (rx_buffer[3]), .SE (n_92), .Q (rx_buffer[3]));
  OA21X1 g4320__5526(.A0 (n_90), .A1 (n_51), .B0 (n_85), .Y (n_86));
  XNOR2X1 g4272__6783(.A (cntr[9]), .B (n_83), .Y (n_84));
  AND2XL g4273__3680(.A (cntr[9]), .B (n_83), .Y (n_87));
  XNOR2X1 g4276__1617(.A (cntr[8]), .B (n_81), .Y (n_82));
  OR4X1 g4324__2802(.A (state), .B (n_46), .C (n_48), .D (n_77), .Y
       (n_85));
  INVX1 g4327(.A (n_92), .Y (n_97));
  AND2XL g4277__1705(.A (cntr[8]), .B (n_81), .Y (n_83));
  OR2X1 g4328__5122(.A (n_90), .B (n_79), .Y (n_92));
  XNOR2X1 g4280__8246(.A (cntr[7]), .B (n_76), .Y (n_80));
  NAND2BX1 g4335__7098(.AN (n_78), .B (rst), .Y (n_79));
  OR4X1 g4329__6131(.A (cntr[15]), .B (n_45), .C (n_65), .D (n_71), .Y
       (n_77));
  AND2XL g4281__1881(.A (cntr[7]), .B (n_76), .Y (n_81));
  XNOR2X1 g4284__5115(.A (cntr[6]), .B (n_74), .Y (n_75));
  AND2XL g4292__7482(.A (cntr[6]), .B (n_74), .Y (n_76));
  NAND3BXL g4343__4733(.AN (n_58), .B (n_63), .C (n_68), .Y (n_78));
  XNOR2X1 g4310__6161(.A (cntr[5]), .B (n_70), .Y (n_73));
  SDFFQX1 \UART_RDR_reg[6] (.CK (clk), .D (rx_buffer[6]), .SI
       (UART_RDR[6]), .SE (n_72), .Q (UART_RDR[6]));
  SDFFQX1 \UART_RDR_reg[2] (.CK (clk), .D (rx_buffer[2]), .SI
       (UART_RDR[2]), .SE (n_72), .Q (UART_RDR[2]));
  SDFFQX1 \UART_RDR_reg[5] (.CK (clk), .D (rx_buffer[5]), .SI
       (UART_RDR[5]), .SE (n_72), .Q (UART_RDR[5]));
  SDFFQX1 \UART_RDR_reg[0] (.CK (clk), .D (rx_buffer[0]), .SI
       (UART_RDR[0]), .SE (n_72), .Q (UART_RDR[0]));
  NAND4XL g4342__9315(.A (n_147), .B (n_6), .C (n_61), .D (n_66), .Y
       (n_71));
  SDFFQX1 \UART_RDR_reg[3] (.CK (clk), .D (rx_buffer[3]), .SI
       (UART_RDR[3]), .SE (n_72), .Q (UART_RDR[3]));
  SDFFQX1 \UART_RDR_reg[1] (.CK (clk), .D (rx_buffer[1]), .SI
       (UART_RDR[1]), .SE (n_72), .Q (UART_RDR[1]));
  SDFFQX1 \UART_RDR_reg[4] (.CK (clk), .D (rx_buffer[4]), .SI
       (UART_RDR[4]), .SE (n_72), .Q (UART_RDR[4]));
  SDFFQX1 \UART_RDR_reg[7] (.CK (clk), .D (rx_buffer[7]), .SI
       (UART_RDR[7]), .SE (n_72), .Q (UART_RDR[7]));
  AND2XL g4311__9945(.A (cntr[5]), .B (n_70), .Y (n_74));
  XNOR2X1 g4325__2883(.A (cntr[4]), .B (n_67), .Y (n_69));
  NOR4X1 g4344__2346(.A (n_47), .B (n_42), .C (n_56), .D (n_57), .Y
       (n_68));
  AND2XL g4326__1666(.A (cntr[4]), .B (n_67), .Y (n_70));
  AOI221X1 g4347__7410(.A0 (UART_CPB[2]), .A1 (n_49), .B0
       (UART_CPB[1]), .B1 (n_55), .C0 (n_50), .Y (n_66));
  OAI2BB1X1 g4355__6417(.A0N (UART_CPB[9]), .A1N (n_62), .B0 (n_54), .Y
       (n_65));
  XNOR2X1 g4337__5477(.A (cntr[3]), .B (n_59), .Y (n_64));
  AOI211XL g4345__2398(.A0 (UART_CPB[8]), .A1 (n_62), .B0 (n_38), .C0
       (n_37), .Y (n_63));
  NAND2X1 g4346__5107(.A (state), .B (n_52), .Y (n_72));
  AOI221X1 g4361__6260(.A0 (UART_CPB[6]), .A1 (n_41), .B0 (n_25), .B1
       (cntr[5]), .C0 (n_24), .Y (n_61));
  XNOR2X1 g4336__4319(.A (bitcntr[3]), .B (n_11), .Y (n_60));
  AND2XL g4341__8428(.A (cntr[3]), .B (n_59), .Y (n_67));
  NAND4XL g4358__5526(.A (n_34), .B (n_2), .C (n_17), .D (n_5), .Y
       (n_58));
  OAI211X1 g4354__6783(.A0 (n_13), .A1 (cntr[5]), .B0 (n_8), .C0
       (n_26), .Y (n_57));
  OAI211X1 g4351__3680(.A0 (UART_CPB[0]), .A1 (n_55), .B0 (n_9), .C0
       (n_20), .Y (n_56));
  AOI221X1 g4360__1617(.A0 (UART_CPB[10]), .A1 (n_44), .B0
       (UART_CPB[8]), .B1 (n_43), .C0 (n_29), .Y (n_54));
  XNOR2X1 g4348__2802(.A (cntr[2]), .B (n_35), .Y (n_53));
  NOR2BX1 g4350__1705(.AN (rst), .B (n_51), .Y (n_52));
  OAI221X1 g4356__5122(.A0 (UART_CPB[3]), .A1 (n_30), .B0
       (UART_CPB[2]), .B1 (n_49), .C0 (n_32), .Y (n_50));
  OAI211X1 g4357__8246(.A0 (n_16), .A1 (cntr[11]), .B0 (n_7), .C0
       (n_4), .Y (n_48));
  OAI222X1 g4365__7098(.A0 (n_19), .A1 (cntr[3]), .B0 (UART_CPB[1]),
       .B1 (n_49), .C0 (n_31), .C1 (cntr[1]), .Y (n_47));
  OAI222X1 g4364__6131(.A0 (UART_CPB[12]), .A1 (n_36), .B0
       (UART_CPB[13]), .B1 (n_15), .C0 (n_33), .C1 (cntr[12]), .Y
       (n_46));
  OAI222X1 g4363__1881(.A0 (UART_CPB[10]), .A1 (n_44), .B0
       (UART_CPB[8]), .B1 (n_43), .C0 (UART_CPB[9]), .C1 (n_62), .Y
       (n_45));
  OAI222X1 g4366__5115(.A0 (UART_CPB[7]), .A1 (n_43), .B0
       (UART_CPB[5]), .B1 (n_41), .C0 (n_22), .C1 (cntr[7]), .Y (n_42));
  MX2XL g4349__7482(.A (bitcntr[2]), .B (n_39), .S0 (n_10), .Y (n_40));
  OAI222X1 g4367__4733(.A0 (n_0), .A1 (cntr[10]), .B0 (UART_CPB[8]),
       .B1 (n_62), .C0 (n_27), .C1 (cntr[11]), .Y (n_38));
  OAI221X1 g4359__6161(.A0 (UART_CPB[10]), .A1 (n_28), .B0
       (UART_CPB[11]), .B1 (n_36), .C0 (n_3), .Y (n_37));
  AND2XL g4353__9315(.A (cntr[2]), .B (n_35), .Y (n_59));
  AOI22X1 g4370__9945(.A0 (n_33), .A1 (cntr[13]), .B0 (UART_CPB[13]),
       .B1 (n_119), .Y (n_34));
  AOI22X1 g4369__2883(.A0 (n_31), .A1 (cntr[0]), .B0 (UART_CPB[3]), .B1
       (n_30), .Y (n_32));
  OAI22X1 g4368__2346(.A0 (UART_CPB[11]), .A1 (n_28), .B0 (n_27), .B1
       (cntr[10]), .Y (n_29));
  AOI22X1 g4373__1666(.A0 (n_25), .A1 (cntr[6]), .B0 (UART_CPB[6]), .B1
       (n_23), .Y (n_26));
  OAI22X1 g4375__7410(.A0 (UART_CPB[7]), .A1 (n_23), .B0 (n_22), .B1
       (cntr[6]), .Y (n_24));
  NAND4XL g4362__6417(.A (bitcntr[3]), .B (bitcntr[0]), .C (n_21), .D
       (n_39), .Y (n_51));
  AOI22X1 g4376__5477(.A0 (n_19), .A1 (cntr[3]), .B0 (UART_CPB[0]), .B1
       (n_55), .Y (n_20));
  MX2XL g4377__2398(.A (n_21), .B (bitcntr[1]), .S0 (bitcntr[0]), .Y
       (n_18));
  AOI22X1 g4378__5107(.A0 (n_16), .A1 (cntr[12]), .B0 (UART_CPB[12]),
       .B1 (n_15), .Y (n_17));
  AOI22X1 g4384__4319(.A0 (cntr[0]), .A1 (n_49), .B0 (cntr[1]), .B1
       (n_55), .Y (n_12));
  OR2XL g4352__8428(.A (n_39), .B (n_10), .Y (n_11));
  XNOR2X1 g4374__5526(.A (UART_CPB[2]), .B (cntr[2]), .Y (n_9));
  XNOR2X1 g4372__6783(.A (UART_CPB[4]), .B (cntr[4]), .Y (n_8));
  XNOR2X1 g4371__3680(.A (UART_CPB[14]), .B (cntr[13]), .Y (n_7));
  XNOR2X1 g4380__1617(.A (UART_CPB[4]), .B (cntr[3]), .Y (n_6));
  XNOR2X1 g4383__2802(.A (UART_CPB[15]), .B (cntr[15]), .Y (n_5));
  XNOR2X1 g4382__1705(.A (UART_CPB[15]), .B (cntr[14]), .Y (n_4));
  XNOR2X1 g4381__5122(.A (UART_CPB[9]), .B (cntr[9]), .Y (n_3));
  XNOR2X1 g4385__8246(.A (UART_CPB[14]), .B (cntr[14]), .Y (n_2));
  NOR2X1 g4386__7098(.A (n_49), .B (n_55), .Y (n_35));
  NAND2X1 g4387__6131(.A (bitcntr[1]), .B (bitcntr[0]), .Y (n_10));
  INVXL g4388(.A (UART_CPB[1]), .Y (n_31));
  INVX1 g4394(.A (cntr[10]), .Y (n_28));
  INVX1 g4408(.A (cntr[6]), .Y (n_23));
  INVX1 g4407(.A (cntr[9]), .Y (n_44));
  INVX1 g4406(.A (cntr[2]), .Y (n_30));
  INVXL g4403(.A (UART_CPB[11]), .Y (n_27));
  INVXL g4389(.A (UART_CPB[3]), .Y (n_19));
  INVX1 g4405(.A (cntr[11]), .Y (n_36));
  INVX1 g4398(.A (cntr[7]), .Y (n_43));
  INVX1 g4409(.A (cntr[8]), .Y (n_62));
  INVX1 g4399(.A (state), .Y (n_90));
  INVXL g4390(.A (UART_CPB[10]), .Y (n_0));
  INVXL g4391(.A (UART_CPB[13]), .Y (n_33));
  INVX1 g4410(.A (cntr[12]), .Y (n_15));
  INVXL g4392(.A (UART_CPB[6]), .Y (n_25));
  INVXL g4402(.A (UART_CPB[7]), .Y (n_22));
  INVXL g4401(.A (UART_CPB[5]), .Y (n_13));
  INVX1 g4397(.A (cntr[5]), .Y (n_41));
  INVXL g4400(.A (UART_CPB[12]), .Y (n_16));
  INVX1 g4412(.A (cntr[13]), .Y (n_119));
  INVX1 g4393(.A (bitcntr[1]), .Y (n_21));
  INVX1 g4404(.A (bitcntr[2]), .Y (n_39));
  INVX1 g4411(.A (cntr[0]), .Y (n_55));
  INVX1 g4396(.A (cntr[1]), .Y (n_49));
  MXI2XL g2(.A (UART_CPB[5]), .B (n_13), .S0 (cntr[4]), .Y (n_147));
endmodule

