
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul 19 2024 12:24:57 CEST (Jul 19 2024 10:24:57 UTC)

// Verification Directory fv/UART 

module UART(rx, clk, rst, tx);
  input rx, clk, rst;
  output tx;
  wire rx, clk, rst;
  wire tx;
  assign tx = 1'b0;
endmodule

